%% Figures for paper 1:
% load all required runs here, then filter out some for each figure;
figs = runArray({ ...
    'runew-36-sym/', ...
    'runew-64361/', ...
    'runew-4341/', ...
                });
%% Center-tracks
figs.filter = [];

figs.plot_penetration;
