%% Figures for paper 1:
% load all required runs here, then filter out some for each figure;
figs = runArray({ ...
    'runew-4341/', ...
    'runew-36-sym/', ...
    'runew-6362-2', ...
    'runew-64361/', ...
                });
figs.name = {'L_{sl}/L > 1', 'L_{sl}/L ~ 1', 'L_{sl}/L < 1', 'L_{sl}/L < 1'};

%% Center-tracks
figs.filter = [];

figs.plot_penetration;
export_fig('images/paper1/centrack.pdf');